name: main

on: push

# ref, https://github.com/microsoft/playwright/issues/5767#issuecomment-907288113
env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Skip downloading during yarn install
  PLAYWRIGHT_BROWSERS_PATH: 0 # Places binaries to node_modules/@playwright/test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
            npx playwright install-deps
      - name: Setup
        run: |
            npm ci
            npx playwright install
      - name: Run E2E tests
        run:
          npm run check:test:e2e
